"""
Florida Disaster Risk Prediction Platform
Main entry point for Streamlit app
"""

import streamlit as st
import requests
import os
from datetime import datetime

from county_data import fetch_county_names
from theme import inject_theme
from views import map as map_page
from views import chatbot as chatbot_page
from views import ocean_tracker as ocean_tracker_page

API_URL = os.getenv("API_URL", "http://127.0.0.1:8000")

PAGE_HOME = "Home"
PAGE_MAP = "Risk Map"
PAGE_OCEAN = "Ocean Tracker"
PAGE_AI = "AI Assistant"
_PAGE_OPTIONS = (PAGE_HOME, PAGE_MAP, PAGE_OCEAN, PAGE_AI)

# Sidebar + Quick Stats: single list (label, info URL)
DATA_SOURCES: list[tuple[str, str]] = [
    ("USGS Earthquakes", "https://earthquake.usgs.gov/"),
    ("NOAA Hurricanes", "https://www.nhc.noaa.gov/"),
    ("NWS Weather Data", "https://www.weather.gov/"),
    ("NCEP GFS (NOMADS)", "https://nomads.ncep.noaa.gov/"),
    ("FDEM (Florida Disaster)", "https://www.floridadisaster.org/"),
]

st.set_page_config(
    page_title="Florida Disaster Risk Prediction",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

inject_theme()

# Migrate old sidebar labels (emoji) after theme update
_OLD_PAGE_LABELS = {
    "🏠 Home": PAGE_HOME,
    "🗺️ Risk Map": PAGE_MAP,
    "🌊 Ocean Tracker": PAGE_OCEAN,
    "💬 AI Assistant": PAGE_AI,
}
if st.session_state.get("sidebar_radio") in _OLD_PAGE_LABELS:
    st.session_state.sidebar_radio = _OLD_PAGE_LABELS[st.session_state.sidebar_radio]


def _qp_first(val) -> str | None:
    if val is None:
        return None
    if isinstance(val, list):
        return str(val[0]).strip() if val else None
    return str(val).strip() or None


def _all_query_params() -> dict:
    """Streamlit 1.28: use experimental_get_query_params; 1.30+ has st.query_params."""
    try:
        qp = st.query_params
        out: dict = {}
        for k in qp.keys():
            v = qp.get(k)
            if isinstance(v, list):
                out[k] = v
            elif v is None:
                out[k] = []
            else:
                out[k] = [v]
        return out
    except AttributeError:
        return dict(st.experimental_get_query_params())


def _geo_url_targets_ai_assistant() -> bool:
    """True when geolocation redirect (?nav=ai or ?lat=&lon=) should open AI Assistant."""
    raw = _all_query_params()
    nav = _qp_first(raw.get("nav"))
    if nav in ("ai", "assistant", "chatbot"):
        return True
    lat = _qp_first(raw.get("lat"))
    lon = _qp_first(raw.get("lon"))
    return bool(lat and lon)


def _sync_sidebar_with_geo_url() -> None:
    """
    Open AI Assistant when the URL indicates a geo / nav landing — once per URL signature.
    Do not reset the sidebar on every rerun while lat/lon query params remain, or navigation appears stuck.
    """
    raw = _all_query_params()
    sig = (
        _qp_first(raw.get("nav")),
        _qp_first(raw.get("lat")),
        _qp_first(raw.get("lon")),
    )
    if st.session_state.get("_geo_url_nav_sig") == sig:
        if "sidebar_radio" not in st.session_state:
            st.session_state.sidebar_radio = PAGE_HOME
        return
    if "sidebar_radio" not in st.session_state:
        st.session_state.sidebar_radio = PAGE_HOME
    if _geo_url_targets_ai_assistant():
        st.session_state.sidebar_radio = PAGE_AI
    st.session_state._geo_url_nav_sig = sig


@st.cache_data(ttl=3600)
def _fetch_county_list(api_base: str) -> list:
    return fetch_county_names(api_base)


def show_home():
    st.markdown("### Welcome")
    st.markdown(
        "This site brings together **Florida hazard data**, **maps**, and **outlooks** in one place. "
        "The **AI Assistant** (chatbot) uses an LLM only to answer questions and guide you—it is not the source of map or forecast data."
    )

    c1, c2 = st.columns([2, 1])

    with c1:
        st.markdown("#### What you can do")
        st.markdown(
            """
- **Risk Map** — Inland hazard markers (USGS + NWS): risk %, type, short outlook window  
- **Ocean Tracker** — Tropical-style outlook for Florida when systems are active  
- **AI Assistant** — Chatbot only: questions, preparedness, and safety guidance  
"""
        )
        st.markdown("#### Data behind the scenes")
        st.caption(
            "Feeds and references include USGS, NOAA/NHC, NWS, NOMADS, and FDEM links in the sidebar—not generated by the chatbot."
        )

    with c2:
        st.markdown("#### Quick stats")

        n_counties = len(_fetch_county_list(API_URL))
        st.metric("Florida counties", n_counties)
        st.metric("Evacuation tiers", 3, "Zones A / B / C")
        st.metric(
            "Data sources",
            len(DATA_SOURCES),
            "USGS · NOAA · NWS · …",
        )


st.markdown(
    """
<div class="main-header">
  <div class="main-header-inner">
    <span class="main-header-icon material-symbols-outlined" title="Disaster preparedness"
          aria-hidden="true">shield_person</span>
    <div class="main-header-text">
      <h1>Florida Disaster Risk Prediction</h1>
      <p class="main-header-sub">Hazard data, maps, and a conversational assistant for residents</p>
    </div>
  </div>
</div>
""",
    unsafe_allow_html=True,
)

with st.sidebar:
    st.markdown(
        '<p class="sidebar-heading"><span class="material-symbols-outlined">menu_book</span> Navigation</p>',
        unsafe_allow_html=True,
    )
    _sync_sidebar_with_geo_url()
    page = st.radio(
        "Page",
        list(_PAGE_OPTIONS),
        label_visibility="collapsed",
        key="sidebar_radio",
    )

    st.divider()

    st.markdown(
        '<p class="sidebar-heading"><span class="material-symbols-outlined">dns</span> System status</p>',
        unsafe_allow_html=True,
    )
    try:
        response = requests.get(f"{API_URL}/health", timeout=2)
        if response.status_code == 200:
            st.success("Backend connected", icon=":material/cloud_done:")
            st.caption(f"API: {API_URL}")
        else:
            st.warning("Backend returned an error", icon=":material/error_outline:")
    except Exception:
        st.error("Backend unreachable", icon=":material/wifi_off:")
        st.caption("Make sure backend is running at 127.0.0.1:8000")

    st.divider()

    st.markdown(
        '<p class="sidebar-heading"><span class="material-symbols-outlined">database</span> Data sources</p>',
        unsafe_allow_html=True,
    )
    for label, url in DATA_SOURCES:
        st.markdown(f"- [{label}]({url})")

    st.divider()

    st.markdown(
        '<p class="sidebar-heading"><span class="material-symbols-outlined">schedule</span> Update schedule</p>',
        unsafe_allow_html=True,
    )
    st.markdown("**Every 7 days**")
    st.caption(f"Last update: {datetime.now().strftime('%Y-%m-%d')}")

if page == PAGE_HOME:
    show_home()
elif page == PAGE_MAP:
    map_page.show()
elif page == PAGE_OCEAN:
    ocean_tracker_page.show()
elif page == PAGE_AI:
    chatbot_page.show()
