"""
Florida Disaster Risk Prediction Platform
Main entry point for Streamlit app
"""

import streamlit as st
import requests
import os
from datetime import datetime

from county_data import fetch_county_names
from views import map as map_page
from views import chatbot as chatbot_page
from views import ocean_tracker as ocean_tracker_page

API_URL = os.getenv("API_URL", "http://127.0.0.1:8000")

# Sidebar + Quick Stats: single list (label, info URL)
DATA_SOURCES: list[tuple[str, str]] = [
    ("USGS Earthquakes", "https://earthquake.usgs.gov/"),
    ("NOAA Hurricanes", "https://www.nhc.noaa.gov/"),
    ("NWS Weather Data", "https://www.weather.gov/"),
    ("NCEP GFS (NOMADS)", "https://nomads.ncep.noaa.gov/"),
    ("FDEM (Florida Disaster)", "https://www.floridadisaster.org/"),
]

st.set_page_config(
    page_title="Florida Disaster Risk Prediction",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)


@st.cache_data(ttl=3600)
def _fetch_county_list(api_base: str) -> list:
    return fetch_county_names(api_base)


def show_home():
    st.markdown("### Welcome")
    st.markdown(
        "This site brings together **Florida hazard data**, **maps**, and **outlooks** in one place. "
        "The **AI Assistant** (chatbot) uses an LLM only to answer questions and guide you—it is not the source of map or forecast data."
    )

    c1, c2 = st.columns([2, 1])

    with c1:
        st.markdown("#### What you can do")
        st.markdown(
            """
- 🗺️ **Risk Map** — Inland hazard markers (USGS + NWS): risk %, type, short outlook window  
- 🌊 **Ocean Tracker** — Tropical-style outlook for Florida when systems are active  
- 💬 **AI Assistant** — Chatbot only: questions, preparedness, and safety guidance  
"""
        )
        st.markdown("#### Data behind the scenes")
        st.caption(
            "Feeds and references include USGS, NOAA/NHC, NWS, NOMADS, and FDEM links in the sidebar—not generated by the chatbot."
        )

    with c2:
        st.markdown("#### 📊 Quick stats")

        n_counties = len(_fetch_county_list(API_URL))
        st.metric("📍 Florida Counties", n_counties)
        st.metric("⚡ Evacuation tiers", 3, "Zones A / B / C")
        st.metric(
            "📡 Data sources",
            len(DATA_SOURCES),
            "USGS · NOAA · NWS · …",
        )


st.markdown(
    """
<style>
    .stApp {
        background: #ffffff !important;
    }
    [data-testid="stHeader"] {
        background: #ffffff !important;
        border-bottom: 1px solid #d6ebf5 !important;
    }
    [data-testid="stSidebar"] {
        background: linear-gradient(180deg, #fbfdff 0%, #f0f7fb 100%) !important;
        border-right: 1px solid #cfe8f2 !important;
    }
    [data-testid="stSidebar"] .block-container {
        padding-top: 0.75rem;
    }
    /* Tighter top; bottom padding also set with emergency footer block below */
    .main .block-container {
        padding-top: 0.5rem !important;
        padding-bottom: 0.5rem !important;
    }
    section[data-testid="stMain"] > div {
        padding-top: 0 !important;
    }
    .main-header {
        background: linear-gradient(135deg, #e8f4fc 0%, #d4ecf7 50%, #cfe9f5 100%);
        padding: 1rem 1.25rem;
        border-radius: 14px;
        color: #1e4a5c;
        margin-bottom: 1rem;
        margin-top: 0;
        border: 1px solid #b8d9ea;
        box-shadow: 0 2px 12px rgba(120, 180, 210, 0.12);
    }
    .main-header-inner {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 1.25rem;
        flex-wrap: wrap;
    }
    .main-header-icon {
        font-size: 4.25rem;
        line-height: 1;
        filter: drop-shadow(0 2px 4px rgba(30,80,120,0.2));
    }
    .main-header-text {
        text-align: center;
    }
    .main-header h1 {
        font-size: 1.6rem;
        font-weight: 700;
        margin: 0;
        color: #0d3d52;
    }
    .main-header .main-header-sub {
        margin: 0.4rem 0 0 0;
        color: #3d6a7d;
        font-size: 0.98rem;
    }
</style>
""",
    unsafe_allow_html=True,
)

st.markdown(
    """
<div class="main-header">
  <div class="main-header-inner">
    <span class="main-header-icon" title="Disaster preparedness">🛡️</span>
    <div class="main-header-text">
      <h1>Florida Disaster Risk Prediction</h1>
      <p class="main-header-sub">Hazard data, maps, and a conversational assistant for residents</p>
    </div>
  </div>
</div>
""",
    unsafe_allow_html=True,
)

with st.sidebar:
    st.markdown("#### 🧭 Navigation")
    page = st.radio(
        "Page",
        [
            "🏠 Home",
            "🗺️ Risk Map",
            "🌊 Ocean Tracker",
            "💬 AI Assistant",
        ],
        label_visibility="collapsed",
    )

    st.divider()

    st.markdown("#### 🔌 System status")
    try:
        response = requests.get(f"{API_URL}/health", timeout=2)
        if response.status_code == 200:
            st.success("✅ Backend Connected")
            st.caption(f"API: {API_URL}")
        else:
            st.warning("⚠️ Backend Issue")
    except Exception:
        st.error("❌ Backend Disconnected")
        st.caption("Make sure backend is running at 127.0.0.1:8000")

    st.divider()

    st.markdown("#### 📡 Data sources")
    for label, url in DATA_SOURCES:
        st.markdown(f"- [{label}]({url})")

    st.divider()

    st.markdown("#### 📅 Update schedule")
    st.markdown("**Every 7 days**")
    st.caption(f"Last update: {datetime.now().strftime('%Y-%m-%d')}")

# Emergency footer — all pages (Risk Map included); extra bottom padding so content clears the bar
st.markdown(
    """
<style>
    .main .block-container { padding-bottom: 4rem !important; }
    .app-fixed-footer {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        z-index: 10000;
        display: flex;
        justify-content: center;
        align-items: center;
        background: linear-gradient(180deg, #e8f4fc 0%, #d4e9f5 100%);
        border-top: 2px solid #9ccfe0;
        padding: 0.65rem 1rem;
        font-size: 0.95rem;
        font-weight: 600;
        color: #0d3d52;
        box-shadow: 0 -2px 12px rgba(80, 140, 170, 0.12);
    }
    .app-fixed-footer-inner {
        text-align: center;
        max-width: min(100%, 52rem);
        margin: 0 auto;
        padding: 0 0.25rem;
    }
</style>
<div class="app-fixed-footer"><span class="app-fixed-footer-inner">Emergency: Call 911 if you are in immediate danger.</span></div>
""",
    unsafe_allow_html=True,
)

if page == "🏠 Home":
    show_home()
elif page == "🗺️ Risk Map":
    map_page.show()
elif page == "🌊 Ocean Tracker":
    ocean_tracker_page.show()
elif page == "💬 AI Assistant":
    chatbot_page.show()
