"""
Florida Disaster Risk Prediction Platform
Main entry point for Streamlit app
"""

import streamlit as st
import requests
import os
from datetime import datetime

from county_data import fetch_county_names
from views import map as map_page
from views import chatbot as chatbot_page
from views import ocean_tracker as ocean_tracker_page

API_URL = os.getenv("API_URL", "http://127.0.0.1:8000")

# Sidebar + Quick Stats: single list (label, info URL)
DATA_SOURCES: list[tuple[str, str]] = [
    ("USGS Earthquakes", "https://earthquake.usgs.gov/"),
    ("NOAA Hurricanes", "https://www.nhc.noaa.gov/"),
    ("NWS Weather Data", "https://www.weather.gov/"),
    ("NCEP GFS (NOMADS)", "https://nomads.ncep.noaa.gov/"),
    ("FDEM (Florida Disaster)", "https://www.floridadisaster.org/"),
]

st.set_page_config(
    page_title="Florida Disaster Risk Prediction",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

_PAGE_OPTIONS = (
    "🏠 Home",
    "🗺️ Risk Map",
    "🌊 Ocean Tracker",
    "💬 AI Assistant",
)


def _qp_first(val) -> str | None:
    if val is None:
        return None
    if isinstance(val, list):
        return str(val[0]).strip() if val else None
    return str(val).strip() or None


def _all_query_params() -> dict:
    """Streamlit 1.28: use experimental_get_query_params; 1.30+ has st.query_params."""
    try:
        qp = st.query_params
        out: dict = {}
        for k in qp.keys():
            v = qp.get(k)
            if isinstance(v, list):
                out[k] = v
            elif v is None:
                out[k] = []
            else:
                out[k] = [v]
        return out
    except AttributeError:
        return dict(st.experimental_get_query_params())


def _geo_url_targets_ai_assistant() -> bool:
    """True when geolocation redirect (?nav=ai or ?lat=&lon=) should open AI Assistant."""
    raw = _all_query_params()
    nav = _qp_first(raw.get("nav"))
    if nav in ("ai", "assistant", "chatbot"):
        return True
    lat = _qp_first(raw.get("lat"))
    lon = _qp_first(raw.get("lon"))
    return bool(lat and lon)


def _sync_sidebar_with_geo_url() -> None:
    """
    Open AI Assistant when the URL indicates a geo / nav landing — once per URL signature.
    Do not reset the sidebar on every rerun while lat/lon query params remain, or navigation appears stuck.
    """
    raw = _all_query_params()
    sig = (
        _qp_first(raw.get("nav")),
        _qp_first(raw.get("lat")),
        _qp_first(raw.get("lon")),
    )
    if st.session_state.get("_geo_url_nav_sig") == sig:
        if "sidebar_radio" not in st.session_state:
            st.session_state.sidebar_radio = "🏠 Home"
        return
    if "sidebar_radio" not in st.session_state:
        st.session_state.sidebar_radio = "🏠 Home"
    if _geo_url_targets_ai_assistant():
        st.session_state.sidebar_radio = "💬 AI Assistant"
    st.session_state._geo_url_nav_sig = sig


@st.cache_data(ttl=3600)
def _fetch_county_list(api_base: str) -> list:
    return fetch_county_names(api_base)


def show_home():
    st.markdown("### Welcome")
    st.markdown(
        "This site brings together **Florida hazard data**, **maps**, and **outlooks** in one place. "
        "The **AI Assistant** (chatbot) uses an LLM only to answer questions and guide you—it is not the source of map or forecast data."
    )

    c1, c2 = st.columns([2, 1])

    with c1:
        st.markdown("#### What you can do")
        st.markdown(
            """
- 🗺️ **Risk Map** — Inland hazard markers (USGS + NWS): risk %, type, short outlook window  
- 🌊 **Ocean Tracker** — Tropical-style outlook for Florida when systems are active  
- 💬 **AI Assistant** — Chatbot only: questions, preparedness, and safety guidance  
"""
        )
        st.markdown("#### Data behind the scenes")
        st.caption(
            "Feeds and references include USGS, NOAA/NHC, NWS, NOMADS, and FDEM links in the sidebar—not generated by the chatbot."
        )

    with c2:
        st.markdown("#### 📊 Quick stats")

        n_counties = len(_fetch_county_list(API_URL))
        st.metric("📍 Florida Counties", n_counties)
        st.metric("⚡ Evacuation tiers", 3, "Zones A / B / C")
        st.metric(
            "📡 Data sources",
            len(DATA_SOURCES),
            "USGS · NOAA · NWS · …",
        )


st.markdown(
    """
<style>
    .stApp {
        background: #ffffff !important;
    }
    [data-testid="stHeader"] {
        background: #ffffff !important;
        border-bottom: 1px solid #d6ebf5 !important;
    }
    [data-testid="stSidebar"] {
        background: linear-gradient(180deg, #fbfdff 0%, #f0f7fb 100%) !important;
        border-right: 1px solid #cfe8f2 !important;
        z-index: 100010 !important;
    }
    [data-testid="stSidebar"] .block-container {
        padding-top: 0.75rem;
    }
    .main .block-container {
        padding-top: 0.5rem !important;
        padding-bottom: 0.5rem !important;
    }
    section[data-testid="stMain"] > div {
        padding-top: 0 !important;
    }
    .main-header {
        background: linear-gradient(135deg, #e8f4fc 0%, #d4ecf7 50%, #cfe9f5 100%);
        padding: 1rem 1.25rem;
        border-radius: 14px;
        color: #1e4a5c;
        margin-bottom: 1rem;
        margin-top: 0;
        border: 1px solid #b8d9ea;
        box-shadow: 0 2px 12px rgba(120, 180, 210, 0.12);
    }
    .main-header-inner {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 1.25rem;
        flex-wrap: wrap;
    }
    .main-header-icon {
        font-size: 4.25rem;
        line-height: 1;
        filter: drop-shadow(0 2px 4px rgba(30,80,120,0.2));
    }
    .main-header-text {
        text-align: center;
    }
    .main-header h1 {
        font-size: 1.6rem;
        font-weight: 700;
        margin: 0;
        color: #0d3d52;
    }
    .main-header .main-header-sub {
        margin: 0.4rem 0 0 0;
        color: #3d6a7d;
        font-size: 0.98rem;
    }
</style>
""",
    unsafe_allow_html=True,
)

st.markdown(
    """
<div class="main-header">
  <div class="main-header-inner">
    <span class="main-header-icon" title="Disaster preparedness">🛡️</span>
    <div class="main-header-text">
      <h1>Florida Disaster Risk Prediction</h1>
      <p class="main-header-sub">Hazard data, maps, and a conversational assistant for residents</p>
    </div>
  </div>
</div>
""",
    unsafe_allow_html=True,
)

with st.sidebar:
    st.markdown("#### 🧭 Navigation")
    _sync_sidebar_with_geo_url()
    page = st.radio(
        "Page",
        list(_PAGE_OPTIONS),
        label_visibility="collapsed",
        key="sidebar_radio",
    )

    st.divider()

    st.markdown("#### 🔌 System status")
    try:
        response = requests.get(f"{API_URL}/health", timeout=2)
        if response.status_code == 200:
            st.success("✅ Backend Connected")
            st.caption(f"API: {API_URL}")
        else:
            st.warning("⚠️ Backend Issue")
    except Exception:
        st.error("❌ Backend Disconnected")
        st.caption("Make sure backend is running at 127.0.0.1:8000")

    st.divider()

    st.markdown("#### 📡 Data sources")
    for label, url in DATA_SOURCES:
        st.markdown(f"- [{label}]({url})")

    st.divider()

    st.markdown("#### 📅 Update schedule")
    st.markdown("**Every 7 days**")
    st.caption(f"Last update: {datetime.now().strftime('%Y-%m-%d')}")

if page == "🏠 Home":
    show_home()
elif page == "🗺️ Risk Map":
    map_page.show()
elif page == "🌊 Ocean Tracker":
    ocean_tracker_page.show()
elif page == "💬 AI Assistant":
    chatbot_page.show()
